name: CI

on:
  push:
    paths-ignore:
    - '**.md'
    branches-ignore:
    - 'master'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        emacs_version: [25.3, 26.3, 27.1]

    steps:
    - uses: actions/checkout@v1

    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - name: versions
      run: |
        emacs --version

    - name: test
      run: |
        make -C test-rbxlx-env
